### PR TITLE
Added github actions for building

### PR DESCRIPTION
**Pull request by Markos-Th09**
I made some github actions to build binaries for a Windows, MacOS and Linux for a lot of common cpu architectures

### CODE REVIEW

**Review by Maiori44 — APPROVED** [review]
Interesting, I never actually used github actions so I guess this is a good time to try them out

**Comment by Maiori44** [comment]
@Markos-Th09 
image
I tried it out and there seems to be an issue, did I mess something up?

**Comment by Markos-Th09** [comment]
It only works on releases

**Comment by Maiori44** [comment]
> It only works on releases at least the last steps of each job you still get the artifacts though

How do I run it on a release?

**Comment by Markos-Th09** [comment]
> > It only works on releases at least the last steps of each job you still get the artifacts though
> 
> How do I run it on a release?

Just create a new release and it will run

**Comment by Maiori44** [comment]
> > > It only works on releases at least the last steps of each job you still get the artifacts though
> > 
> > 
> > How do I run it on a release?
> 
> Just create a new release and it will run. It is made like this so it puts the files in the release. It is triggered every time a release is created

Ohh I see, sorry for the dumb question then lol

**Pull request merged**
