### PR TITLE
Remove rpmalloc from core

### PR DESCRIPTION
**Pull request by Markos-Th09**
As clue_core is a library, the allocator choice should be left to the user instead of using rpmalloc by default.

### CODE REVIEW

**Comment by Maiori44** [comment]
Is this a breaking change?

**Comment by Markos-Th09** [comment]
> Is this a breaking change?

I don't think changing the allocator is a breaking change, since the api is completely backwards compatible and this is only an internal detail.

**Comment by Maiori44** [comment]
So it should be included in the patch?

**Comment by Markos-Th09** [comment]
> So it should be included in the patch?

I am not entirely sure if this is considered a minor or a patch but let's go with patch.

**Review by Rosy-iso — APPROVED** [review]
seems alright

**Pull request merged**
