### PR TITLE
fix: Make --execute work with --pathiscode

### PR DESCRIPTION
**Pull request by Markos-Th09**

### CODE REVIEW

**Review by Maiori44 — CHANGES_REQUESTED** [review]
{}s should be separated with a space from the rest of the code.   
Also, would this be for a 2.5.3 or?

**Comment by Markos-Th09** [comment]
> {}s should be separated with a space from the rest of the code. Also, would this be for a 2.5.3 or?

Yes 2.5.3 and for some reason rustfmt didn't work let me fix that

**Review by Markos-Th09 — COMMENTED** [review]
Done

**Review by Maiori44 — APPROVED** [review]
Okay, works now, but what would 2.5.3 be? Should it only have this?

**Comment by Markos-Th09** [comment]
> 

yeah but if we find more bugs we should fix them

**Comment by Maiori44** [comment]
I'll merge this but wait before releasing, in case more bugs are found

**Comment by Markos-Th09** [comment]
> I'll merge this but wait before releasing, in case more bugs are found

I will test all combinations of options later. I have to finish a project.

**Comment by Maiori44** [comment]
Alright.

**Comment by Markos-Th09** [comment]
> Alright.

no other bugs related to flags, we are good to go

**Comment by Maiori44** [comment]
Maybe we should still wait, just in case

**Comment by Markos-Th09** [comment]
> Maybe we should still wait, just in case

Also I should not this doesn't have to be backported to 3.0, it already has this fix

**Comment by Maiori44** [comment]
Uh actually, that's bad.
We shouldn't have backported it into 2.5.

**Pull request merged**
