### PR TITLE
Refactored `ParseTokens` for readability

### PR DESCRIPTION
**Pull request by Enn3Developer**
I created some new methods for `ParserInfo` with all the functions I extrapolated from `ParseTokens` and called them inside the `match` in `ParseTokens`

### CODE REVIEW

**Review by Maiori44 — COMMENTED** [review]
are some of these functions really needed? I can get the idea for big match branches, but functions like parse_token_fn_enum feel like a bit of a waste

there's also the inconsistent casing with the previous functions but that's for another time

**Comment by Enn3Developer** [comment]
> are some of these functions really needed?
That's just to be consistent with the branches

> there's also the inconsistent casing with the previous functions
I can fix it now, but the current casing isn't standard Rust

**Comment by Maiori44** [comment]
wdym with consistent with the branches?

**Comment by Enn3Developer** [comment]
I prefer reading
```rust
branch1 => func1(),
branch2 => func2(),
branch3 => func3(),
```
Instead of
```rust
branch1 => func1(),
branch2 => { code() }
branch3 => func3(),
```
But if you want I can revert some branches

**Comment by Maiori44** [comment]
hm, if we revert some of the branches we can't enstablish a method to decide which should be a function and which a branch, basically it'd be not only inconsistent but also messy lol

**Comment by Maiori44** [comment]
so yeah I decided to merge this, I guess
we'll need to think about the casing next

**Pull request merged**
