### PR TITLE
Remove ENV_DATA

### PR DESCRIPTION
**Pull request by Markos-Th09**
Mutable global state makes the code less flexible and can cause problems with performance.

### CODE REVIEW

**Review by Maiori44 — COMMENTED** [review]
If the compiler must use a struct, might as well bring all the other variables that the functions pass between eachothers to that struct?

**Comment by Markos-Th09** [comment]
> If the compiler must use a struct, might as well bring all the other variables that the functions pass between eachothers to that struct?

it is not a must but it is just easier

**Comment by Maiori44** [comment]
> > If the compiler must use a struct, might as well bring all the other variables that the functions pass between eachothers to that struct?
> 
> it is not a must but it is just easier

I guess I could do that myself later..

**Comment by Markos-Th09** [comment]
now I updated the whole thing to use references

**Review by Maiori44 — COMMENTED** [review]
This seems okay, but I really dislike the new compiler
I'll probably undo the struct after I merge it, it's really pointless...

**Comment by Markos-Th09** [comment]
> This seems okay, but I really dislike the new compiler
> I'll probably undo the struct after I merge it, it's really pointless...

I disagree that it is pointless and trust me you are going to get to some very annoying parameter drillign

**Comment by Maiori44** [comment]
> > This seems okay, but I really dislike the new compiler
> > I'll probably undo the struct after I merge it, it's really pointless...
> 
> I disagree that it is pointless and trust me you are going to get to some very annoying parameter drilling

it's only used for a single variable that only some functions use
and I remember having a ton of issues with the struct when doing the parser while the compiler was really easy to do

**Comment by Markos-Th09** [comment]
> > > This seems okay, but I really dislike the new compiler
> > > I'll probably undo the struct after I merge it, it's really pointless...
> > 
> > 
> > I disagree that it is pointless and trust me you are going to get to some very annoying parameter drilling
> 
> it's only used for a single variable that only some functions use and I remember having a ton of issues with the struct when doing the parser while the compiler was really easy to do
> 
> parameter drilling doesn't annoy me at all, it's a quick and easy chore to do



> > > This seems okay, but I really dislike the new compiler
> > > I'll probably undo the struct after I merge it, it's really pointless...
> > 
> > 
> > I disagree that it is pointless and trust me you are going to get to some very annoying parameter drilling
> 
> it's only used for a single variable that only some functions use and I remember having a ton of issues with the struct when doing the parser while the compiler was really easy to do
> 
> parameter drilling doesn't annoy me at all, it's a quick and easy chore to do

It think this approach makes the code less maintainable

**Comment by Maiori44** [comment]
> > > > This seems okay, but I really dislike the new compiler
> > > > I'll probably undo the struct after I merge it, it's really pointless...
> > > 
> > > 
> > > I disagree that it is pointless and trust me you are going to get to some very annoying parameter drilling
> > 
> > 
> > it's only used for a single variable that only some functions use and I remember having a ton of issues with the struct when doing the parser while the compiler was really easy to do
> > parameter drilling doesn't annoy me at all, it's a quick and easy chore to do
> 
> > > > This seems okay, but I really dislike the new compiler
> > > > I'll probably undo the struct after I merge it, it's really pointless...
> > > 
> > > 
> > > I disagree that it is pointless and trust me you are going to get to some very annoying parameter drilling
> > 
> > 
> > it's only used for a single variable that only some functions use and I remember having a ton of issues with the struct when doing the parser while the compiler was really easy to do
> > parameter drilling doesn't annoy me at all, it's a quick and easy chore to do
> 
> It think this approach makes the code less maintainable and harder to change

and yet it's structs that made the parser harder to change

**Review by Maiori44 — APPROVED** [review]
After thinking about, I decided to give the struct a shot
I really hope it works

**Pull request merged**
