### PR TITLE
Formatted code

### PR DESCRIPTION
**Pull request by Enn3Developer**
Formatted the code using `cargo fmt`

### CODE REVIEW

**Review by Markos-Th09 — CHANGES_REQUESTED** [review]
The TokenType should be ignored by rustfmt as it is easier to read the way it is.

**Comment by Enn3Developer** [comment]
Fixed

**Comment by Enn3Developer** [comment]
I reverted TokenType

**Review by Maiori44 — CHANGES_REQUESTED** [review]
If I recall correctly there should be a way to setup the formatter to make it format using 4 tabs indentation instead of 4 spaces, but I never did it so I don't know how
if you could do that it'd be great

**Comment by Enn3Developer** [comment]
Now it should be all good

**Review by Maiori44 — APPROVED** [review]
it seems like it didn't fix the indentation in the macros' definitions, but I can just fix that myself later
I'll merge this now

**Pull request merged**
